### ISSUE TITLE
PCB/Schematic design files

### ISSUE THREAD

**Issue by DRSDavidSoft** [Gamadril/BLE-Nixie#1]
Hello, @Gamadril 

I've been following up your blog, and this repo seems amazing! I'm however unable to acquire your CRONIXIE kits, but I'm interested to build one based on the STM32 platform and BLE WT51822-S4AT module.

To get me starting, I was wondering if your project PCB design files were also open-source, which I could then use in my project. Is it possible to share your project design files (on GitHub or Mediafire) to start working on them?

Thanks for your time.

**Comment by Gamadril** [comment]
Hello David,
sorry, but I'm not producing those kits. I'm just looking for ways using them in own projects and make interesting combination with other technologies like Web Bluetooth.
